service: feedbin-to-pinboard

plugins:
  - serverless-pseudo-parameters
  - serverless-offline
  - serverless-offline-scheduler

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: us-west-1
  profile: default
  environment:
    REGION: ${self:provider.region}
    STAGE: ${self:provider.stage}
    ACCOUNTID: '#{AWS::AccountId}'
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "lambda:InvokeFunction"
      Resource: "*"
    - Effect: "Allow"
      Resource: "*"
      Action:
        - "sns:*"
package:
  include:
    - utils/**
functions:
  get_ids:
    handler: handler.getIds
    events:
      - schedule:
          name: ${self:provider.stage}.check-feedbin
          description: 'Checks the feedbin url every 5 minutes'
          rate: rate(5 minutes)
  get_items:
    handler: handler.getItems
    events:
      - http:
          path: item
          method: post
  getItems:
    handler: getItems.handler
    events:
      - sns: get-items-topic # created immediately
    onError: arn:aws:sns:#{AWS::Region}:#{AWS::AccountId}:dlq-topic
  error:
    handler: error.handler
    events:
      - sns: dlq-topic # created immediately
