service: feedbin-to-pinboard

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs6.10
  stage: ${opt:stage, 'dev'}
  region: us-west-1
  profile: default
package:
  include:
    - utils/**
functions:
  getIds:
    handler: handler.getIds
    events:
      - http:
          path: ids
          method: get
  getItems:
    handler: handler.getItems
    events:
      - http:
          path: item
          method: post
  createBookmark:
    handler: handler.createBookmark
    events:
      - http:
          path: bookmark
          method: post
  unstarItems:
    handler: handler.unstarItems
    events:
      - http:
          path: unstar
          method: delete
