service: feedbin-to-pinboard

plugins:
  - serverless-offline
  - serverless-offline-scheduler

provider:
  name: aws
  runtime: nodejs6.10
  stage: ${opt:stage, 'dev'}
  region: us-west-1
  profile: default
package:
  include:
    - utils/**
functions:
  get_ids:
    handler: handler.getIds
    events:
      - schedule:
          name: check-feedbin
          description: 'Checks the feedbin url every 5 minutes'
          rate: rate(5 minutes)
  get_items:
    handler: handler.getItems
    events:
      - http:
          path: item
          method: post
  create_bookmark:
    handler: handler.createBookmark
    events:
      - http:
          path: bookmark
          method: post
  unstar_items:
    handler: handler.unstarItems
    events:
      - http:
          path: unstar
          method: delete
